id: P7F777C62
initial_creation_type: input
source_metadata:
  title: Rigdzin Gödem
  language: de
  description: 'Texts by and about Rigdzin Gödem Ngödrup Gyaltsen (rig ''dzin rgod
    ldem dngos grub rgyal mtshan, 1337–1408), famed discoverer of the so-called Northern
    Treasures (byang gter) revelation:'
  volume:
    1f7f47ba9ca34961815e03a09b4f3a66:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Aspiration Prayers
    b9b50dca675646349634bd7b38ebc42b:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    9b301131a6b74f589458f27cd28e188d:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    4bd58710803c4b3a9acd04edaade10fd:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    45e0ae2088394e99ae3a6f155e8eda98:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    1ed2e25147a1434fbd2f5a9b53c9716d:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    b37ce7a5a30f4882b1a475e28b54d731:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    c5661ab8705d403ba6e832d575d29ec1:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    85d88bb5ca224f899cea7838094d7152:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Practices
    6419c44fbd564bd29d0b81e94d4a1e15:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Sādhanas
created_at: '2022-03-01T01:21:42.533905'
last_modified_at: '2022-03-01T01:21:42.533908'
